### ISSUE TITLE
How to use Native Instance

### ISSUE THREAD

**Issue by TranQuangMinh** [bensladden/vue-fabric-wrapper#104]
Hi guy thanks for lib.
i want use "canvas.getActiveObject().to Group();" but i not found document to resolve this problem.

Please help me.

**Comment by bensladden** [comment]
Hi, See example
[https://codesandbox.io/s/stickman-scdpz?file=/src/App.vue](https://codesandbox.io/s/stickman-scdpz?file=/src/App.vue)

I am debating creating a component that passes the fabric instance as a prop and use .sync on it but not had the time yet

**Comment by TranQuangMinh** [comment]
Thanks you :)
