### ISSUE TITLE
How to use Fabric methods in Nuxt project

### ISSUE THREAD

**Issue by taungyeon** [bensladden/vue-fabric-wrapper#106]
Hello. Thank you for the great library.

I would like to use ‘fabric.Canvas#toJSON()’ but I cannot access it in Nuxt.js.

Could you tell me what should I do?
Thanks.

**Comment by bensladden** [comment]
Hi have you tried #104 ?

**Comment by taungyeon** [comment]
I'm glad to get your reply.

Of course, I gave it try.
I created GetImage.vue and executed the project, but the following error occurred.
```
  ERROR  [Vue warn]: Injection "$canvas" not found
```
I did on the developping environment below.
```
     "nuxt": "^2.0.0",
```

I would appreciated if you help me.
Thanks you.

**Comment by bensladden** [comment]
Did you do the following first:
https://github.com/bensladden/vue-fabric-wrapper#-how-to-use-in-nuxt

**Comment by taungyeon** [comment]
YES. of course!

plugin, nuxt.config and .vue
I checked many times.

best regards.

**Comment by bensladden** [comment]
[https://codesandbox.io/s/great-merkle-cs7of?file=/pages/index.vue](https://codesandbox.io/s/great-merkle-cs7of?file=/pages/index.vue)

**Comment by bensladden** [comment]
working example

**Comment by taungyeon** [comment]
Thank you so much!
this solves my problem.
