### ISSUE TITLE
Creating Fabric Components that use FabricCanvas

### ISSUE THREAD

**Issue by michaelbrawn** [bensladden/vue-fabric-wrapper#107]
Hey @bensladden 

Is it possible to create "complex" components that use the canvas from FabricCanvas using vue's `mounted` or `watch`? 

It looks like `mounted` is called on child components before the parent. Is there a way to have the child components re-render once fabric is initialized? The goal would be to create several components (Grid, Tile, etc https://jsfiddle.net/rekrah/q0xe7yfz/). 

Here's an example code sandbox where the goal would be to draw the grid once fabric is loaded.
https://codesandbox.io/s/stickman-dd77e?file=/src/components/FabridGrid.vue

**Comment by bensladden** [comment]
Hi michael,
Yes it is, you can access the fabric canvas via
`inject: ["$canvas", "$group", "fabric"],`
and then a computed prop:
`
computed: {
    canvas() {
      return this.$canvas();
    },
}
`


Once the canvas prop is defined you can do any complex component.
This may be of help:
[https://github.com/bensladden/vue-fabric-wrapper/blob/master/src/components/FabricLineGrid.vue](https://github.com/bensladden/vue-fabric-wrapper/blob/master/src/components/FabricLineGrid.vue)

**Comment by alukos** [comment]
```ERROR  [Vue warn]: Injection "$canvas" not found```
https://github.com/bensladden/vue-fabric-wrapper/issues/106#issuecomment-627269081
