### ISSUE TITLE
fabric-svg-from-url

### ISSUE THREAD

**Issue by constructivetim** [bensladden/vue-fabric-wrapper#111]
all my other components work fine, but when i use

`<fabric-svg-from-url :id="'someUUID'"></fabric-svg-from-url>`

I get 

Unknown custom element: `<fabric-svg-from-url>` - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by bensladden** [comment]
import FabricSvgFromUrl from "./components/FabricSVGFromURL";
components: {
    FabricSvgFromUrl,
  }

See: [https://github.com/bensladden/vue-fabric-wrapper/blob/master/src/App.vue](https://github.com/bensladden/vue-fabric-wrapper/blob/master/src/App.vue)

**Comment by constructivetim** [comment]
This worked, I copied the components from github down to a local directory ./components.  it is not clear that i should have to do this when I have used npm install to install vue-fabric?

**Comment by bensladden** [comment]
Hi, sorry to be clear you don’t need to copy the components but in the
components object the name was changed to better fit the HTML casing

**Comment by constructivetim** [comment]
so, if I just do this:

<fabric-image-from-url url="/pitch2.png"/>
...
  import vueFabricWrapper from "vue-fabric-wrapper";
...
  export default {
    components: {
      FabricImageFromUrl: FabricImageFromURL
    },
...

i get

ReferenceError: FabricImageFromURL is not defined

**Comment by bensladden** [comment]
import vueFabricWrapper from "vue-fabric-wrapper"; ... export default {
components: { FabricImageFromUrl: vueFabricWrapper.FabricImageFromURL },

**Comment by constructivetim** [comment]
brilliant.  that fixed it.  thanks ben
