### ISSUE TITLE
How to pass props as objects ? instead passing single props

### ISSUE THREAD

**Issue by aditya-umang** [bensladden/vue-fabric-wrapper#120]
Currently im using this systax to define props
`<fabric-canvas borderColor:"#ff0000",>`

i need to pass all props as options
`<fabric-canvas :options="canvas_options">`
where 
```
canvas_options: {
       borderColor:"#ff0000",
       backgroundColor:"00ff00"
}
```

is it possible ??

**Comment by bensladden** [comment]
Hi use the following: [https://vuejs.org/v2/guide/components-props.html#Passing-the-Properties-of-an-Object](https://vuejs.org/v2/guide/components-props.html#Passing-the-Properties-of-an-Object)
