### ISSUE TITLE
Border props dont work

### ISSUE THREAD

**Issue by utglobal** [bensladden/vue-fabric-wrapper#71]
The given border props do not seem to work:

```
      <fabric-canvas
        :width="1280"
        :height="720"
        :borderColor="red">
        <fabric-circle :id="3"></fabric-circle>
      </fabric-canvas>
```

Since `hasBorders` is default to true shouldn't this add a little red border or I am missing something?

**Comment by bensladden** [comment]
Solution: [https://codesandbox.io/s/debug-z591o](https://codesandbox.io/s/debug-z591o)
not sure if you wanted the border on the circle (which is stroke) or if you wanted the drag box border to be red so i have done both (click on the blue circle to see it)

**Comment by bensladden** [comment]
BTW if you want the border of the canvas to be red you would do this via the standard html way with style or via the vue style methods [https://vuejs.org/v2/guide/class-and-style.html](https://vuejs.org/v2/guide/class-and-style.html)
