### ISSUE TITLE
Component to draw with brush

### ISSUE THREAD

**Issue by utglobal** [bensladden/vue-fabric-wrapper#72]
I am trying to simply draw on the canvas.
How can I achieve that.

This does not work

`this.canvas.freeDrawingBrush.width = 5;
this.canvas.freeDrawingBrush.color = '#00aeff';`

It is not able to find the freeDrawingBrush object.

**Comment by bensladden** [comment]
The wrapper at this stage does not does not currently support free drawing. 
[http://fabricjs.com/freedrawing](http://fabricjs.com/freedrawing) provides some examples. You wont be able to access the canvas object unless you are creating a component inside the canvas slot. Then you can access it via injecting it into your custom compnent.  i.e. inside you component 

```vue
export default {
inject: ["$canvas"],
computed: {
    canvas() {
      return this.$canvas();
    }
}

```

**Comment by lextoc** [comment]
I'm trying to achieve this. Could you go into further detail with this?
