### ISSUE TITLE
Image From Url component doesn't work

### ISSUE THREAD

**Issue by locallyaccepted** [bensladden/vue-fabric-wrapper#78]
Editing question:

When I  put <fabric-image-from-URL id="testUID"></fabric-image-from-URL>

and in data

data: function(){
  return {
    testUID: 'google storage url'
  }
}

The image doesn't load at all. Any idea why this would be the case? 

Thank you

**Comment by bensladden** [comment]
Hi, you will need to set the url for the component to work. The default for this prop is ../vue.png so if this file does not exist in your vue project it will not load.

**Comment by locallyaccepted** [comment]
I noticed that upon looking further. Thank you for the reply.

I do have one more question.

If I put a string url in the :url section, it loads correctly, but if I have the url as a reactive property (ie a computed property), no image is loading. 

Thank you for your responses :) I'm not a programmer by trade, learning out of budget necessity to build tools for my shop

**Comment by bensladden** [comment]
Not sure what is wrong here is an example: [https://codesandbox.io/s/debug-eqeyv](https://codesandbox.io/s/debug-eqeyv)

**Comment by locallyaccepted** [comment]
https://codesandbox.io/s/debug-4kfd1

I replicated the issue I'm having. Nothing throws in the console, the object updates correctly but the image doesn't.

Once again, thank you so much for your help :)

**Comment by bensladden** [comment]
Ahh i see your problem. The url prop does not refresh the image. To get around this see below:
[https://codesandbox.io/s/debug-gf460](https://codesandbox.io/s/debug-gf460)
Basically don't render the component unless the url is set.
If you wish to swap the url once rendered you will most likely need to set the prop back to "" then wait for next tick before setting it again.

**Comment by bensladden** [comment]
example: [https://codesandbox.io/s/debug-f5buh](https://codesandbox.io/s/debug-f5buh)

**Comment by locallyaccepted** [comment]
Thank you so much :)
