### ISSUE TITLE
How to use Fabric methods

### ISSUE THREAD

**Issue by johnny-longneck** [bensladden/vue-fabric-wrapper#80]
I am trying to get started with the vue wrapper for fabric js. I have experience in fabric but not that much with vue.

How can I set a background Image for a fabricjs-canvas made by the wrapper?

```<FabricCanvas></FabricCanvas>```

Is in the template. How to access it?

**Comment by bensladden** [comment]
I had forgotten about this. In the most recent release (0.3.63) i have just made a component for this purpose.
Example [https://codesandbox.io/s/stickman-nh6ng](https://codesandbox.io/s/stickman-nh6ng)

**Comment by bensladden** [comment]
Also to access other methods see below:

[https://codesandbox.io/s/stickman-scdpz](https://codesandbox.io/s/stickman-scdpz)

Look at the GetImage component

**Comment by johnny-longneck** [comment]
Thank you. It works, awesome support!
