### ISSUE TITLE
How to get fabric canvas to use canvas.toDataUrl

### ISSUE THREAD

**Issue by locallyaccepted** [bensladden/vue-fabric-wrapper#81]
Hello again

Fairly simple question. Say I were to have a canvas

<fabric-canvas id="front"></fabric-canvas>

How would I go about selecting that canvas component by id in my vue methods so I could perform the action similar to below?

var dataURL = canvas.toDataURL({
  format: 'jpeg',
  quality: 0.8
});

Cheers and thank you!

**Comment by bensladden** [comment]
You can write a child component that can access the canvas.
[https://codesandbox.io/s/stickman-scdpz](https://codesandbox.io/s/stickman-scdpz)

Look at the GetImage component

**Comment by locallyaccepted** [comment]
Thank you!

Is there a way to select the <fabric-canvas> by id though? I'm going to have four canvases (one for front, back, left, and right mockups so I figure I'll do one button and loop to get all mockups same time)

Cheers :)

**Comment by bensladden** [comment]
See updated example: https://codesandbox.io/s/stickman-scdpz

Note this is a new event just added
