### ISSUE TITLE
Syncing properties of Fabric Component

### ISSUE THREAD

**Issue by johnny-longneck** [bensladden/vue-fabric-wrapper#82]
Hello, 
Unfortunatly I have to open another ticket:

I have a v-for Loop of a Data Array which is rendered here:

```
<FabricCanvas :id="'canvas'+index" :height="500" :width="500" :ref="'canvas'+index">
     <FabricRectangle :id="view.id" fill="transparent"  stroke="rgba(149,193,31,1)" :left.sync="view.xpos" :top.sync="view.ypos" :width.sync="view.width" :height.sync=view.height></FabricRectangle>
</FabricCanvas>
```

I could get the top and left values to be updating correctly, but it is not working with width and height.
Is this a missing feature or is it working differently?

Nice to have: How to round updated values?
I get top and left then like: 99.1201000111 as value

Thanks again for your work.

Edit: I Also noticed that the watch observer for views is not triggered when values have been updated via fabric component. (But corresponding input fields for top and left do react)

**Comment by bensladden** [comment]
Hi,
You are correct the width and height may not update depending on your interaction. However the scaleX and scaleY parameters are most likely being modified. See [http://fabricjs.com/events](http://fabricjs.com/events) and watch what happens to the props when you move and scale the objects.

Sorry im not sure what you mean by "watch observer for views"

Rounding numbers could be achieved via watching the props from the parent.

**Comment by johnny-longneck** [comment]
Thanks again for your support. This solves my question.
