### ISSUE TITLE
Feature: Typescript definitions missed

### ISSUE THREAD

**Issue by angelfraga** [bensladden/vue-fabric-wrapper#88]
I have recently installed it then I noticed typescript definitions are not included.
I have tried `npm i -D @types/vue-fabric-wrapper` but it looks that they don't exist yet.

I think it would be great to have those definitions in order to allow easier development in typescript environments.

Thanks for the library.

**Comment by bensladden** [comment]
Hi, Yes this would be good to have. I am not that experienced in creating definition file for vue components so if you or anyone else knows the best place to start feel free to contrubute.

**Comment by bensladden** [comment]
Started a branch: https://github.com/bensladden/vue-fabric-wrapper/tree/typescriptdefs
But will require assistance to finish it off

**Comment by angelfraga** [comment]
> Hi, Yes this would be good to have. I am not that experienced in creating a definition file for vue components so if you or anyone else knows the best place to start feel free to contrubute.

**Comment by angelfraga** [comment]
Me too, but we could have a look at other vue library repositories.
