### ISSUE TITLE
Not able to load SVG from local url

### ISSUE THREAD

**Issue by sidh01** [bensladden/vue-fabric-wrapper#93]
I am tring to load svg in fabric from local url but it seems to be not working for me.
can someone please help me.
I have created sample code here
https://codesandbox.io/s/damp-waterfall-s8ism

![image](https://user-images.githubusercontent.com/37957105/75880979-4fede800-5e44-11ea-9f26-dc7f01c70eb3.png)

**Comment by bensladden** [comment]
Please see here: [https://codesandbox.io/s/xenodochial-resonance-jidvk](https://codesandbox.io/s/xenodochial-resonance-jidvk)

Note i have used fabric image as fabricfrom svg did not like the svg for some reason. This is fine providing you do not wish to ungroup and interact with the svg.

**Comment by bensladden** [comment]
Sorry did not mean to close it without response

**Comment by sidh01** [comment]
I want each part of this to be editable that's why I have loaded this using url and added as a object group if I load using image then element are not separated as its an image and I can't edit.

**Comment by bensladden** [comment]
I would try to use this without the wrapper (i.e. use fabric by itself without fabric-wrapper) and see if it works first. I suspect this svg is not compatible being loaded in this mode.

**Comment by bensladden** [comment]
As you don't appear to be using the fabric wrapper  as per comment above perhaps do this:
[https://codesandbox.io/s/billowing-bash-k2u5g](https://codesandbox.io/s/billowing-bash-k2u5g)

**Comment by sidh01** [comment]
But we are not able to select individual svg element like text .
I want to select individual element and change there font family,color etc
